<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-Q90AFIM" failures="2" tests="6" name="Test" time="0.948" errors="0" timestamp="2022-11-20T20:11:50 IST">
  <testcase classname="testNG.Retry_Runner" name="IOOB" time="0.303">
    <skipped/>
  </testcase> <!-- IOOB -->
  <testcase classname="testNG.Retry_Runner" name="IOOB" time="0.01">
    <skipped/>
  </testcase> <!-- IOOB -->
  <testcase classname="testNG.Retry_Runner" name="IOOB" time="0.016">
    <failure type="java.lang.StringIndexOutOfBoundsException" message="String index out of range: 6">
      <![CDATA[java.lang.StringIndexOutOfBoundsException: String index out of range: 6
at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:48)
at java.base/java.lang.String.charAt(String.java:1515)
at testNG.Retry_Runner.IOOB(Retry_Runner.java:10)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- IOOB -->
  <testcase classname="testNG.Retry_Runner" name="exception" time="0.014">
    <skipped/>
  </testcase> <!-- exception -->
  <testcase classname="testNG.Retry_Runner" name="exception" time="0.008">
    <skipped/>
  </testcase> <!-- exception -->
  <testcase classname="testNG.Retry_Runner" name="exception" time="0.018">
    <failure type="org.testng.TestException" message="
Method Retry_Runner.exception()[pri:0, instance:testNG.Retry_Runner@6676f6a0] should have thrown an exception of type class java.lang.IndexOutOfBoundsException">
      <![CDATA[org.testng.TestException: 
Method Retry_Runner.exception()[pri:0, instance:testNG.Retry_Runner@6676f6a0] should have thrown an exception of type class java.lang.IndexOutOfBoundsException
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- exception -->
</testsuite> <!-- Test -->
